export const REQUEST_CITIES = "REQUEST_CITIES";
export const RECEIVE_CITIES = "RECEIVE_CITIES";
export const FAILED_CITIES = "FAILED_CITIES";

export const REQUEST_OPENWEATHER = "REQUEST_OPENWEATHER";
export const RECEIVE_OPENWEATHER = "RECEIVE_OPENWEATHER";
export const FAILED_OPENWEATHER = "FAILED_OPENWEATHER";
